"""Add ProjectFeature

Revision ID: 075c10edcdff
Revises: f04422b4c127
Create Date: 2026-09-06 15:50:48.262907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075c10edcdff'
down_revision: Union[str, Sequence[str], None] = 'f04422b4c127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_project_id', sa.String(), nullable=True),
    sa.Column('reporting_date', sa.Date(), nullable=True),
    sa.Column('progress_variance_pct', sa.Float(), nullable=True),
    sa.Column('progress_completion_ratio', sa.Float(), nullable=True),
    sa.Column('progress_velocity', sa.Float(), nullable=True),
    sa.Column('progress_acceleration', sa.Float(), nullable=True),
    sa.Column('expenditure_ratio', sa.Float(), nullable=True),
    sa.Column('monthly_expenditure_rate', sa.Float(), nullable=True),
    sa.Column('expenditure_growth', sa.Float(), nullable=True),
    sa.Column('cost_progress_divergence', sa.Float(), nullable=True),
    sa.Column('financial_physical_divergence', sa.Float(), nullable=True),
    sa.Column('schedule_progress_gap', sa.Float(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('time_overrun_days', sa.Integer(), nullable=True),
    sa.Column('time_overrun_pct', sa.Float(), nullable=True),
    sa.Column('delay_momentum', sa.Float(), nullable=True),
    sa.Column('milestone_completion_ratio', sa.Float(), nullable=True),
    sa.Column('milestone_delay_rate', sa.Float(), nullable=True),
    sa.Column('issue_pressure', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_momentum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['internal_project_id'], ['projects.internal_project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_features_id'), 'project_features', ['id'], unique=False)
    op.create_index(op.f('ix_project_features_internal_project_id'), 'project_features', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_project_features_reporting_date'), 'project_features', ['reporting_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_features_reporting_date'), table_name='project_features')
    op.drop_index(op.f('ix_project_features_internal_project_id'), table_name='project_features')
    op.drop_index(op.f('ix_project_features_id'), table_name='project_features')
    op.drop_table('project_features')
    # ### end Alembic commands ###
