"""Initial Phase 1 schema

Revision ID: f04422b4c127
Revises: 
Create Date: 2026-09-06 15:44:20.901976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04422b4c127'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('internal_project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('ministry', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('original_end_date', sa.Date(), nullable=True),
    sa.Column('revised_end_date', sa.Date(), nullable=True),
    sa.Column('original_cost_cr', sa.Float(), nullable=True),
    sa.Column('revised_cost_cr', sa.Float(), nullable=True),
    sa.Column('project_code', sa.String(), nullable=True),
    sa.Column('legacy_ocms_code', sa.String(), nullable=True),
    sa.Column('pmgid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('internal_project_id')
    )
    op.create_index(op.f('ix_projects_internal_project_id'), 'projects', ['internal_project_id'], unique=False)
    op.create_table('issues',
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('internal_project_id', sa.String(), nullable=True),
    sa.Column('reporting_date', sa.Date(), nullable=True),
    sa.Column('issue_category', sa.String(), nullable=True),
    sa.Column('issue_description', sa.String(), nullable=True),
    sa.Column('issue_status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['internal_project_id'], ['projects.internal_project_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_issues_internal_project_id'), 'issues', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_issues_issue_id'), 'issues', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issues_reporting_date'), 'issues', ['reporting_date'], unique=False)
    op.create_table('milestones',
    sa.Column('milestone_id', sa.String(), nullable=False),
    sa.Column('internal_project_id', sa.String(), nullable=True),
    sa.Column('milestone_name', sa.String(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['internal_project_id'], ['projects.internal_project_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_index(op.f('ix_milestones_internal_project_id'), 'milestones', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_milestones_milestone_id'), 'milestones', ['milestone_id'], unique=False)
    op.create_table('project_snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('internal_project_id', sa.String(), nullable=True),
    sa.Column('reporting_date', sa.Date(), nullable=True),
    sa.Column('planned_progress_pct', sa.Float(), nullable=True),
    sa.Column('physical_progress_pct', sa.Float(), nullable=True),
    sa.Column('planned_expenditure_cr', sa.Float(), nullable=True),
    sa.Column('period_expenditure_cr', sa.Float(), nullable=True),
    sa.Column('cumulative_expenditure_cr', sa.Float(), nullable=True),
    sa.Column('milestones_planned', sa.Integer(), nullable=True),
    sa.Column('milestones_completed', sa.Integer(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['internal_project_id'], ['projects.internal_project_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_project_snapshots_internal_project_id'), 'project_snapshots', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_project_snapshots_reporting_date'), 'project_snapshots', ['reporting_date'], unique=False)
    op.create_index(op.f('ix_project_snapshots_snapshot_id'), 'project_snapshots', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_snapshots_snapshot_id'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_reporting_date'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_internal_project_id'), table_name='project_snapshots')
    op.drop_table('project_snapshots')
    op.drop_index(op.f('ix_milestones_milestone_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_internal_project_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_issues_reporting_date'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_internal_project_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_projects_internal_project_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
