import { useEffect, useState } from 'react'
import axios from 'axios'
import { motion } from 'framer-motion'
import { Brain, AlertCircle, CheckCircle2 } from 'lucide-react'

export default function PredictiveML({ projectId }: { projectId: string }) {
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    axios.get("http://127.0.0.1:8000/api/projects/" + projectId + "/predictions")
      .then(res => { setData(res.data); setLoading(false) })
      .catch(() => setLoading(false))
  }, [projectId])

  if (loading) {
    return (
      <div className="glass-panel p-6 flex items-center justify-center h-48 opacity-70">
        <div className="w-8 h-8 border-4 border-amber-200 border-t-amber-600 rounded-full animate-spin" />
      </div>
    )
  }

  if (!data) return null

  const items = [
    { label: 'Cost Overrun Risk', val: data.cost_overrun_prob, color: '#be123c' },
    { label: 'Schedule Delay Risk', val: data.schedule_delay_prob, color: '#b45309' },
    { label: 'Milestone Failure Risk', val: data.milestone_failure_prob, color: '#c2410c' },
    { label: 'Rapid Escalation Risk', val: data.escalation_risk_prob, color: '#be123c' },
  ]

  return (
    <div className="glass-panel overflow-hidden border border-amber-100">
      <div className="absolute top-0 right-0 w-64 h-64 bg-amber-50 rounded-full blur-[80px] pointer-events-none" />
      
      <div className="px-6 py-4 flex items-center justify-between border-b border-amber-100 bg-amber-50/50">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-amber-100 flex items-center justify-center text-amber-700 shadow-sm border border-amber-200">
            <Brain size={16} />
          </div>
          <div>
            <h3 className="text-sm font-black text-slate-800 tracking-wide uppercase">Failure Prediction</h3>
            <p className="text-[10px] text-amber-700 uppercase tracking-widest mt-0.5 flex items-center gap-1 font-bold">
              Predictive ML (Layer 04A)
            </p>
          </div>
        </div>
      </div>

      <div className="p-6 relative z-10 space-y-5">
        {items.map((item, i) => (
          <div key={item.label}>
            <div className="flex justify-between items-end mb-1.5">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest flex items-center gap-1.5">
                {item.val > 50 ? <AlertCircle size={12} className="text-red-500" /> : <CheckCircle2 size={12} className="text-teal-600" />}
                {item.label}
              </span>
              <span className="text-sm font-black tabular-nums" style={{ color: item.val > 50 ? item.color : '#0f766e' }}>
                {item.val}%
              </span>
            </div>
            <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden border border-slate-200/50">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${item.val}%` }}
                transition={{ duration: 1, delay: i * 0.1 }}
                className="h-full rounded-full"
                style={{ backgroundColor: item.val > 50 ? item.color : '#0f766e' }}
              />
            </div>
          </div>
        ))}
        <p className="text-xs text-slate-400 leading-relaxed mt-4 pt-4 border-t border-slate-100">
          Probabilities generated by Random Forest models trained on historical portfolio performance data.
        </p>
      </div>
    </div>
  )
}
