import { useEffect, useState } from 'react'
import axios from 'axios'
import { motion } from 'framer-motion'
import { Brain, AlertCircle, CheckCircle2 } from 'lucide-react'
import API_BASE from '../../config/api'

export default function PredictiveML({ projectId }: { projectId: string }) {
  const [data, setData] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    axios.get(`${API_BASE}/api/projects/` + projectId + "/predictions")
      .then(res => { setData(res.data); setLoading(false) })
      .catch(() => setLoading(false))
  }, [projectId])

  if (loading) {
    return (
      <div className="glass-panel p-6 flex items-center justify-center h-48 opacity-70">
        <div className="w-8 h-8 border-4 border-brand-primary/20 border-t-brand-primary rounded-full animate-spin" />
      </div>
    )
  }

  if (!data) return null

  const items = [
    { label: 'Cost Overrun Risk', val: data.cost_overrun.prob, drivers: data.cost_overrun.drivers, color: '#ef4444' }, // text-coral roughly
    { label: 'Schedule Delay Risk', val: data.schedule_delay.prob, drivers: data.schedule_delay.drivers, color: '#f59e0b' },
    { label: 'Milestone Failure Risk', val: data.milestone_failure.prob, drivers: data.milestone_failure.drivers, color: '#f97316' },
    { label: 'Rapid Escalation Risk', val: data.escalation_risk.prob, drivers: data.escalation_risk.drivers, color: '#ef4444' },
  ]

  return (
    <div className="glass-panel overflow-hidden border border-border-default">
      <div className="absolute top-0 right-0 w-64 h-64 bg-brand-primary/5 rounded-full blur-[80px] pointer-events-none" />
      
      <div className="px-6 py-4 flex items-center justify-between border-b border-border-default bg-brand-primary/5">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-brand-primary/10 flex items-center justify-center text-brand-primary shadow-sm border border-brand-primary/20">
            <Brain size={16} />
          </div>
          <div>
            <h3 className="text-sm font-black text-text-primary tracking-wide uppercase">Failure Prediction & XAI</h3>
            <p className="text-[10px] text-brand-primary uppercase tracking-widest mt-0.5 flex items-center gap-1 font-bold">
              Predictive ML (Layer 04A)
            </p>
          </div>
        </div>
      </div>

      <div className="p-6 relative z-10 space-y-6">
        {items.map((item, i) => (
          <div key={item.label} className="group relative">
            <div className="flex justify-between items-end mb-1.5">
              <span className="text-[10px] font-bold text-text-secondary uppercase tracking-widest flex items-center gap-1.5">
                {item.val > 50 ? <AlertCircle size={12} className="text-coral" /> : <CheckCircle2 size={12} className="text-brand-primary" />}
                {item.label}
              </span>
              <span className="text-sm font-black tabular-nums" style={{ color: item.val > 50 ? item.color : 'var(--brand-primary)' }}>
                {item.val}%
              </span>
            </div>
            <div className="h-2 w-full bg-surface-sunken rounded-full overflow-hidden border border-border-default mb-2">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${item.val}%` }}
                transition={{ duration: 1, delay: i * 0.1 }}
                className="h-full rounded-full"
                style={{ backgroundColor: item.val > 50 ? item.color : 'var(--brand-primary)' }}
              />
            </div>
            
            {/* Feature Drivers (XAI) */}
            {item.drivers && item.drivers.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-2">
                {item.drivers.map((driver: any, idx: number) => (
                  <div key={idx} className="flex items-center gap-1.5 bg-surface-sunken px-2 py-1 rounded text-[9px] font-bold text-text-secondary border border-border-default uppercase tracking-wider">
                    <span>{driver.name}</span>
                    <span className="text-text-muted">|</span>
                    <span className="text-brand-primary">{driver.weight}% Impact</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}
        <p className="text-xs text-text-muted leading-relaxed mt-4 pt-4 border-t border-border-default">
          Probabilities and feature drivers generated by ensemble ML models (XGBoost & LightGBM) trained on historical performance data.
        </p>
      </div>
    </div>
  )
}
